#:import SlideTransition kivy.uix.screenmanager.SlideTransition

<BaseFloatLayout>:
    MainLayout:
        id: main_layout
    WifiLayout:
        id: wifi_layout
        orientation: 'vertical'

        ScreenManager:
            id: wifi_screen_manager
            transition: SlideTransition(duration=0.75)
            
            canvas.before:
                Color:
                    rgba: 0.1, 0.1, 0.1, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

<MainLayout>:
    orientation: 'vertical'
    FloatLayout:
        id: top_layout
        size_hint_y: 3
        canvas.before:
            Color:
                rgba: (0.149, 0.157, 0.231, 1)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20]
        DeckArea:
            id: deck_area_obj
            size_hint: 0.75, 0.75
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    