<DeckButton@ButtonBehavior+RelativeLayout>:
    background_color: (0, 0, 0, 0)  # Прозрачный фон кнопки
    canvas.before:
        # Тень (BoxShadow)
        Color:
            rgba: 0, 0, 0, 0.2
        RoundedRectangle:
            pos: self.x + dp(3), self.y - dp(2)
            size: self.width - dp(2), self.height - dp(2)
            radius: [35]
            #radius: [min(self.width, self.height) * 0.22,]
        # Основной цвет кнопки
        Color:
            rgba: self.anim_color if hasattr(self, 'anim_color') else (0.1, 0.6, 0.9, 1)
        RoundedRectangle:
            pos: self.pos[0] + 2.5, self.pos[1] + 2.5
            size: self.size[0] - 5, self.size[1] - 5
            radius: [35]
            #radius: [min(self.width, self.height) * 0.2,]
    canvas.after:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            texture: self.texture
            size: self.texture_size
            pos: self.center_x - self.texture_size[0]/2, self.center_y - self.texture_size[1]/2

    text: self.emoji if hasattr(self, "emoji") else ''
    font_name: "seguiemj"
    font_size: min(self.width, self.height) * 0.6
    on_size: self.texture_update()
