<DeckButton@Button>:
    background_color: (0, 0, 0, 0)  # Прозрачный фон кнопки
    canvas.before:
        # Тень (BoxShadow)
        Color:
            rgba: 0, 0, 0, 0.2
        RoundedRectangle:
            pos: self.x + dp(3), self.y - dp(2)
            size: self.width - dp(2), self.height - dp(2)
            radius: [35]
            #radius: [min(self.width, self.height) * 0.22,]
        # Основной цвет кнопки
        Color:
            rgba: self.get_hsv_color() if hasattr(self, 'get_hsv_color') else (0.1, 0.6, 0.9, 1)
        RoundedRectangle:
            pos: self.pos[0] + 2.5, self.pos[1] + 2.5
            size: self.size[0] - 5, self.size[1] - 5
            radius: [35]
            #radius: [min(self.width, self.height) * 0.2,]
    # Центрируем содержимое
    BoxLayout:
        orientation: 'vertical'
        pos: self.pos
        size: self.size
        padding: [0, 0, 0, 0]
        spacing: 0
        Image:
            id: btn_img
            source: root.image_source if hasattr(root, 'image_source') and root.image_source else ''
            allow_stretch: True
            keep_ratio: True
            size_hint: (1, 1)
            opacity: 1 if root.image_source else 0
        Label:
            id: btn_emoji
            text: root.emoji if hasattr(root, 'emoji') and root.emoji else ''
            font_size: min(root.width, root.height) * 0.6
            halign: 'center'
            valign: 'middle'
            color: 1, 1, 1, 1
            opacity: 1 if root.emoji and not root.image_source else 0
