<DeckButton@ButtonBehavior+RelativeLayout>:
    background_color: (0, 0, 0, 0)  # Прозрачный фон кнопки
    canvas.before:
        # Тень
        Color:
            rgba: 0, 0, 0, 0.4
        BoxShadow:
            pos: self.pos
            size: self.size
            offset: -0, -6
            spread_radius: -6, -9
            border_radius: [min(self.size[0]/self.grid_w, self.size[1]/self.grid_h) * 0.35, min(self.size[0]/self.grid_w, self.size[1]/self.grid_h) * 0.35, min(self.size[0]/self.grid_w, self.size[1]/self.grid_h) * 0.35, min(self.size[0]/self.grid_w, self.size[1]/self.grid_h) * 0.35]
            blur_radius: min(self.size[0]/self.grid_w, self.size[1]/self.grid_h) * 0.2
        # Основной цвет кнопки
        Color:
            rgba: self.anim_color if hasattr(self, 'anim_color') else (0.1, 0.6, 0.9, 1)
        RoundedRectangle:
            pos: self.pos[0] + 5, self.pos[1] + 5
            size: self.size[0] - 10, self.size[1] - 10
            radius: [min(self.size[0]/self.grid_w, self.size[1]/self.grid_h) * 0.35]
    canvas.after:
        # Иконка
        Color:
            rgba: (1, 1, 1, 1) if self.image_source else (0, 0, 0, 0)
        Rectangle:
            source: "assets/" + self.image_source if self.image_source else ''
            size: [self.size[0] * 0.7, self.size[1] * 0.7] if self.icon_fit_button else [min(self.size[0], self.size[1]) * 0.7, min(self.size[0], self.size[1]) * 0.7]
            pos: [self.center_x - self.size[0]*0.35, self.center_y - self.size[1]*0.35] if self.icon_fit_button else [self.center_x - min(self.size[0], self.size[1])*0.35, self.center_y - min(self.size[0], self.size[1])*0.35]
