<MainLayout>:
    orientation: 'vertical'
    FloatLayout:
        id: top_layout
        size_hint_y: 3
        canvas.before:
            Color:
                rgba: 0.149, 0.156, 0.231, 1
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20]
        DeckArea:
            id: deck_area
            size_hint: 0.6, 0.9
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
    BoxLayout:
        id: bottom_layout
        size_hint_y: 2
        canvas.before:
            Color:
                rgba: 0.7, 0.4, 0.3, 1
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20]
        