<MainLayout>:
    orientation: 'vertical'
    deck_area: deck_area_obj
    FloatLayout:
        id: top_layout
        size_hint_y: 3
        canvas.before:
            Color:
                rgba: (0.149, 0.157, 0.231, 1)
            Rectangle:
                pos: self.pos[0], self.pos[1] - (self.size[1] * 0.2)
                size: self.size[0], self.size[1] * 1.2
        DeckArea:
            id: deck_area_obj
            size_hint: 0.6, 0.9
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        
        AnimatedPlusButton:
            text: '+'
            size_hint: None, None
            size: min(self.parent.height, self.parent.width) * 0.2, min(self.parent.height, self.parent.width) * 0.2
            pos_hint: {'center_x': 0.07, 'center_y': 0.83}
            background_normal: ''
            background_color: [0, 0, 0, 0]
            font_size: self.height * 0.6
            canvas.before:
                Color:
                    rgba: self.anim_color
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [self.height * 0.3,]
    BoxLayout:
        id: bottom_layout
        size_hint_y: 2
        padding: [10, 10, 10, 10]
        canvas.before:
            Color:
                rgba: (0.365, 0.384, 0.565, 1)
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [20, 20, 0, 0]
