<KeyboardButton>:
    foreground_color: [1,1,1,1]
    background_color: [0,0,0,0]
    background_image: ""
    background_normal: ""
    background_active: ""
    font_size: 25
    canvas.before:
        Color:
            rgba: [.2, .2, .2, 1] if root.state == 'normal' else [.3, .3, .3, 1]
        RoundedRectangle:
            pos: self.pos[0] + 2.5, self.pos[1] + 2.5
            size: self.size[0] - 5, self.size[1] - 5
            radius: [15]