<WifiPasswordScreen>:
    name: "wifi_password"

    BoxLayout:
        id: wifi_select_layout
        canvas.before:
            Color:
                rgba: .1, .1, .1, 1
            Rectangle:
                pos: (0, 0)
                size: self.size
    
    Label:
        text: "Введите пароль:"
        pos_hint: {"center_x":.55, "center_y":.87}
        font_size: 30
        text_size: self.size
        halign: 'left'
        valign: 'middle'
    
    TextInput:
        id: password_text_input
        password: False
        multiline: False
        size_hint: 0.7, 0.1
        pos_hint: {"center_x":.5, "center_y":.7}
        halign: "center"
        font_size: 24
        foreground_color: [1,1,1,1]
        background_color: [0,0,0,0]
        background_image: ""
        background_normal: ""
        background_active: ""
        canvas.after:
            Color:
                rgba: .2, .2, .2, .5
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [15]