<WifiPasswordScreen>:
    name: "wifi_password"

    BoxLayout:
        id: wifi_select_layout
        canvas.before:
            Color:
                rgba: .1, .1, .1, 1
            Rectangle:
                pos: (0, 0)
                size: self.size
    
    Label:
        text: "Введите пароль:"
        pos_hint: {"center_x":.55, "center_y":.87}
        font_size: 30
        text_size: self.size
        halign: 'left'
        valign: 'middle'
    
    TextInput:
        id: password_text_input
        password: False
        multiline: False
        size_hint: 0.7, 0.1
        pos_hint: {"center_x":.5, "center_y":.7}
        halign: "center"
        font_size: 24
        foreground_color: [1,1,1,1]
        background_color: [0,0,0,0]
        background_image: ""
        background_normal: ""
        background_active: ""
        canvas.after:
            Color:
                rgba: .2, .2, .2, .5
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [15]

<DoneButton>:
    foreground_color: [1,1,1,1]
    background_color: [0,0,0,0]
    background_image: ""
    background_normal: ""
    background_active: ""
    font_size: 25
    canvas.before:
        Color:
            rgba: [.2, .2, .2, 1] if root.state == 'normal' else [.3, .3, .3, 1]
        RoundedRectangle:
            pos: self.pos[0] + 2.5, self.pos[1] + 2.5
            size: self.size[0] - 5, self.size[1] - 5
            radius: [15]